<?php
/** 
 * GuruWebSoft (www.guruwebsoft.com)
 * 
 * @author     MagentoPycho <rajen_k_bhtt@hotmail.com>
 * @category   Catalog/Product/View
 * @package    MagentoPycho_Lightboxes
 */
?>
<?php
if(Mage::helper('lightboxes')->getConfig('active')):
    $moduleName         = $this->getRequest()->getModuleName();
    $controllerName     = $this->getRequest()->getControllerName();
    $actionName         = $this->getRequest()->getActionName();
    #echo $moduleName . '|' . $controllerName . '|' . $actionName;
    if(Mage::helper('lightboxes')->getConfig('include_globally') || (in_array($moduleName, array('catalog', 'review')) && $controllerName == 'product' && in_array($actionName, array('view', 'list')))):
?>
<?php
//include jQuery file if enabled
if(Mage::helper('lightboxes')->getConfig('include_jquery')):
?>
<script type="text/javascript" src="<?php echo Mage::helper('lightboxes')->getLightboxUrl(); ?>/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo Mage::helper('lightboxes')->getLightboxUrl(); ?>/no-conflict.js"></script>
<?php endif; ?>
<?php
if(Mage::helper('lightboxes')->getConfig('lightbox_type') == 'fancybox'):
    $rel = 'fancybox';
?>
<!-- FancyBox -->
<script type="text/javascript" src="<?php echo Mage::helper('lightboxes')->getLightboxUrl(); ?>/fancybox/jquery.easing-1.3.pack.js"></script>
<script type="text/javascript" src="<?php echo Mage::helper('lightboxes')->getLightboxUrl(); ?>/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<script type="text/javascript" src="<?php echo Mage::helper('lightboxes')->getLightboxUrl(); ?>/fancybox/jquery.fancybox-1.3.2.pack.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo Mage::helper('lightboxes')->getLightboxUrl(); ?>/fancybox/jquery.fancybox-1.3.2.css" media="screen" /> 
<!-- FancyBox -->
<?php
endif; //fancybox
?>
<?php 
    if(Mage::helper('lightboxes')->getConfig('lightbox_type') == 'lightboxclone'):
    $rel = 'lightboxclone';
?>
<!-- Lightbox Clone -->
<script type="text/javascript" src="<?php echo Mage::helper('lightboxes')->getLightboxUrl(); ?>/jquery-lightbox-0.5/js/jquery.lightbox-0.5.min.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo Mage::helper('lightboxes')->getLightboxUrl(); ?>/jquery-lightbox-0.5/css/jquery.lightbox-0.5.css" media="screen" />  
<!-- Lightbox Clone -->
<?php
    endif; //lightboxclone
?>
<?php 
    if(Mage::helper('lightboxes')->getConfig('lightbox_type') == 'pirobox'):
    $rel = '';
    $class = 'pirobox';
    $demo  = Mage::helper('lightboxes')->getConfig('theme', 'pirobox');
?>
<!-- Pirobox -->
<link href="<?php echo Mage::helper('lightboxes')->getLightboxUrl(); ?>/pirobox/css_pirobox/<?php echo $demo; ?>/style.css" class="piro_style" media="screen" title="white" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo Mage::helper('lightboxes')->getLightboxUrl(); ?>/pirobox/js/pirobox.min.js"></script>
<!-- Pirobox -->
<?php
    endif; //pirobox
?>
    <?php endif; ?>
<?php endif; //end active ?>