<?php
$rel                = '';
$class              = '';
$mainImageSize      = $this->getMainImageSize();
$popUpImageSize     = $this->getPopupImageSize();
$thumbnailSize      = $this->getThumbnailImageSize();
if($this->getConfig('lightbox_type') == 'fancybox'):
    $rel = 'fancybox';
?>
<!-- FancyBox -->
<script type="text/javascript">
    jQuery(document).ready(function(){      
        jQuery("a[rel=<?php echo $rel; ?>]").fancybox({            
			<?php echo $this->getFancyboxJsConfig(); ?>
		});

    });
</script>    
<!-- FancyBox -->
<?php
endif;
?>

<?php 
    if($this->getConfig('lightbox_type') == 'lightboxclone'):
    $rel = 'lightboxclone';
?>
<!-- Lightbox Clone -->
<script type="text/javascript">
    jQuery(document).ready(function(){  
        jQuery('a[rel=<?php echo $rel; ?>]').lightBox({               
			<?php echo $this->getLightboxcloneJsConfig(); ?>
		});

    });
</script>    
<!-- Lightbox Clone -->
<?php
    endif;
?>

<?php 
    if($this->getConfig('lightbox_type') == 'pirobox'):
    $rel = '';
    $class = 'pirobox';
    $demo  = $this->getConfig('theme', 'pirobox');
?>
<!-- Pirobox -->
<script type="text/javascript">
    jQuery(document).ready(function(){  
       jQuery().piroBox({               
			<?php echo $this->getPiroboxJsConfig(); ?>
		});

    });
</script>    
<!-- Pirobox -->
<?php
    endif;
?>


<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>

<?php
//check if zoomer is disabled
if($this->getConfig('disable_zoombar')):
?>
<p class="product-image">
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($mainImageSize[0], $mainImageSize[1]).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        if(empty($popUpImageSize[0]) || empty($popUpImageSize[0])):
            $popUpImage = $this->helper('catalog/image')->init($_product, 'image');
        else:
            $popUpImage = $this->helper('catalog/image')->init($_product, 'image')->resize($popUpImageSize[0], $popUpImageSize[1]);
        endif;
       
    ?>
    <a href="<?php echo $popUpImage; ?>" rel="<?php echo $rel; ?>" class="<?php echo $class; ?>" title="<?php echo $this->htmlEscape($this->getImageLabel()) ?>"><?php echo $_helper->productAttribute($_product, $_img, 'image'); ?></a>
</p>
<?php else: ?>
<p class="product-image product-image-zoom">
    <?php
        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<p class="zoom-notice" id="track_hint"><?php echo $this->__('Double click on above image to view full picture') ?></p>
<div class="zoom">
    <img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" title="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
    <div id="track">
        <div id="handle"></div>
    </div>
    <img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" title="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
</div>
<script type="text/javascript">
//<![CDATA[
    Event.observe(window, 'load', function() {
        product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
    });
//]]>
</script>
<?php endif; ?>

<?php else: ?>
<p class="product-image">
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(300,398).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<?php endif; ?>
<?php if (count($this->getGalleryImages()) > 0):
?>
<div class="prosmall-img">
    <ul>
    <?php foreach ($this->getGalleryImages() as $_image): 
            if(empty($popUpImageSize[0]) || empty($popUpImageSize[0])):
                $popUpImage = $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile());
            else:
                $popUpImage = $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($popUpImageSize[0], $popUpImageSize[1]);
            endif;
    ?>
        <li>
            <a href="<?php echo $popUpImage; ?>" rel="<?php echo $rel; ?>" class="<?php echo $class; ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($thumbnailSize[0], $thumbnailSize[1]); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>